config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations', passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # get 'graph', to: 'graphs#search'
  root 'homes#top'

  # updateに「:id」は不要なのでresource「s」ではない事に注意
  resource :graphs, only: %i[create update]
  resources :graphs, only: [:index, :show]
  resources :users, only: [:show, :index, :edit]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user

  VALID_DATA_REGEX = /\A[-]?[0-9]+(\.[0-9]+)?\z/i
  # 一人のユーザーが同じ日付のデータを複数記録できないようにする
  validates :date, presence: true, uniqueness: { scope: :user_id }
  validates :weight, presence: true, format: { with: VALID_DATA_REGEX }

  def self.chart_data(user)
    # そのままデータを取り出すと日付が不連続なデータになる為、日付の連続したデータを作成(asc:昇順)
    graphs = user.graphs.order(date: :asc)
    # 記録が無い場合にエラーが出るのを防止
    return [{ date: Date.today, weight: nil }] if graphs.empty?

    # 記録の初日から最終日までの配列データを作成
    period = graphs[0].date..graphs[-1].date
    index = 0
    period.map { |date|
      if graphs[index].date == date
        weight = graphs[index].weight
        index += 1
      end
      # データが存在しない日付の体重はnilとする
      { date: date, weight: weight }
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :graphs, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A[a-z\d]{6,23}+\z/i
  VALID_DATA_REGEX = /\A[-]?[0-9]+(\.[0-9]+)?\z/i

  validates :email,
            presence: true,
            uniqueness: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX, message: "は半角6文字以上23文字以下英数小文字" }
  validates :username, length: { maximum: 30 }, allow_blank: true
  validates :age, numericality: true, inclusion: { in: 0..150 }, allow_blank: true
  validates :height, numericality: true, format: { with: VALID_DATA_REGEX }, allow_blank: true
  validates :weight, numericality: true, format: { with: VALID_DATA_REGEX }, allow_blank: true
  validates :profile, length: { maximum: 1000 }, allow_blank: true
  validates :target_weight, numericality: true, format: { with: VALID_DATA_REGEX }, allow_blank: true
  validates :target_body, numericality: true, format: { with: VALID_DATA_REGEX }, allow_blank: true

  mount_uploader :avatar, ImageUploader

  def self.guest
    # 指定のemailが見つからない場合createで新規レコード作成
    # !は例外を発生させる(!がないとログインされないままリダイレクトされる)
    find_or_create_by!(email: 'test@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲスト"
      user.age = 20
      user.gender = "男"
      user.height = 160
      user.weight = 55
      user.profile = "ご覧いただきありがとうございます！\r\n健康の為にダイエットを決意いたしました！一緒に頑張りましょう！"
      user.target_weight = 50
      user.target_body = 20
      # user.confirmed_at = Time.now
    end
  end

  # validate :password_complexity
  # def password_complexity
  #   return if password.blank? || password =~ /\A[a-z\d]{6,10}+\z/
  #   errors.add :password, 'の長さは6〜10文字英数小文字'
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 全ページをログイン必須とする
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  # CSRFへの対策
  protect_from_forgery with: :exception

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    if resource.is_a?(AdminUser)
      admin_root_path
    else
      graphs_path
    end
  end

  protected

    def configure_permitted_parameters
      added_attrs = [:email, :password, :password_confirmation]
      devise_parameter_sanitizer.permit :sign_up, keys: [added_attrs, :username]
      devise_parameter_sanitizer.permit :account_update, keys: [added_attrs, :username, :age, :gender, :height, :weight, :profile, :target_weight, :target_body, :avatar]
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  # before_action :set_q, only: [:index, :search]

  def index
    # ransack検索用
    # @q = Graph.ransack(params[:q])
    # @graphs = @q.result(distinct: true).order(date: "DESC")
    # gon.graphs = @q.result(distinct: true).order(date: "DESC")

    # DBにある体重データをJavascriptに渡す
    gon.weight_records = Graph.chart_data(current_user)
    # 記録済みの日付データ
    gon.recorded_dates = current_user.graphs.map(&:date)
  end

  # def search
  #   @q = Graph.search(params_graph_search)
  #   @graphs = @q.result(distinct: true).order(date: "DESC")
    # gon.graphs = @q.result(distinct: true).order(date: "DESC")
  # end

  def show
    # @graphs = User.find(params[:id])
  end

  def create
    @graph = current_user.graphs.build(graph_params)
    date = @graph.date.strftime('%Y/%-m/%-d')
    if @graph.save
      flash[:notice] = "#{date}の記録を追加しました"
    else
      flash[:alert] = 'エラーが発生しました'
    end
    redirect_to graphs_path
  end

  def update
    # 削除ボタンに name 属性を入れたので、削除ボタンを押したときだけ params[:_destroy] が存在する状態となる
    @graph = current_user.graphs.find_by(date: params[:graph][:date])
    date = @graph.date.strftime('%Y/%-m/%-d')
    if @graph.nil?
      flash[:alert] = 'エラーが発生しました'
    elsif params[:_destroy].nil? && @graph.update(graph_params)
      flash[:notice] = "#{date}の記録を修正しました。"
    elsif params[:_destroy].present? && @graph.destroy
      flash[:alert] = "#{date}の記録を削除しました。"
    else
      flash[:alert] = 'エラーが発生しました'
    end
    redirect_to graphs_path
  end

  private

    def graph_params
      params.require(:graph).permit(:date, :weight)
    end

    # def params_graph_search
    #   params.permit(:weight_gt)
    # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'test@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # destroyアクションの動作前に、メールアドレスがゲストユーザー用になっていないかチェック
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'test@example.com'
      redirect_to graphs_path, alert: 'ゲストユーザーは編集・削除できません。'
    end
  end

  # 新規登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    graphs_path
  end
  
  # アカウント編集後のリダイレクト先
  def after_update_path_for(resource)
    graphs_path
  end

  protected

    # パスワードを入れずにアカウント情報を編集できるようにする
    # def after_update_path_for(resource, params)
    #   resource.update_without_password(params)
    # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    # ログイン(deviseのメソッド)
    sign_in user
    redirect_to graphs_path, notice: 'ゲストユーザとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(id: :asc)
  end

  def show
    @user = current_user
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each { |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button typr="button" class="close" data-dismiss="alert">
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    }
    html.html_safe
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphs/_edit_modal_content.html.erb
<%= form_with model: Graph.new, method: :patch do |form| %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">日付</span>
    </div>
    <%= form.text_field :date, class: 'form-control bg-white', id: "edit-calendar" %>
  </div>
  <small>記録が存在しない日付は選択できません</small>
  <div class="input-group mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">体重</span>
    </div>
    <%= form.number_field :weight, class: 'form-control', id: "edit-weight", in: 10.0..200.0, step: '0.1', required: true %>
    <div class="ml-2 my-auto">kg</div>
  </div>
  <small>小数第1位まで記録できます</small>
  <div class="form-group mt-3">
    <%= form.submit '修正', class: 'btn btn-primary btn-block mb-4', id: 'edit-button' %>
    <%= form.submit '削除', name: '_destroy', class: 'btn btn-danger btn-block', id: 'destroy-button', data: { confirm: "本当に記録を削除しますか？" } %>
  </div>
<% end %>

app/views/graphs/_modal.html.erb
<div class="modal fade" id="<%= action %>-modal" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "#{action}_modal_content" %>
      </div>
    </div>
  </div>
</div>

app/views/graphs/_new_modal_content.html.erb
<%= form_with model: Graph.new do |form| %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">日付</span>
    </div>
    <%= form.text_field :date, class: 'form-control bg-white', id: "new-calendar" %>
  </div>
  <small>記録が存在する日付は選択できません</small>
  <div class="input-group mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">体重</span>
    </div>
    <%= form.number_field :weight, class: 'form-control', id: "new-weight", in: 10.0..200.0, step: '0.1', required: true %>
    <div class="ml-2 my-auto">kg</div>
  </div>
  <small>小数第1位まで記録できます</small>
  <div class="form-group mt-3">
    <%= form.submit '新規登録', class: 'btn btn-primary btn-block', id: 'new-button' %>
  </div>
<% end %>

app/views/graphs/index.html.erb
<%= Gon::Base.render_data %>
<div class="row">
  <div class="col-6">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#new-modal">
      新規登録
    </button>
  </div>
  <div class="col-6">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#edit-modal">
      記録の修正
    </button>
  </div>
</div>
<%= render 'modal', action: 'new', title: '新規登録' %>
<%= render 'modal', action: 'edit', title: '修正' %>

<div class="row no-gutters">
  <div class="input-group col-sm-6 pr-sm-3 mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">開始</span>
    </div>
    <input type="text" id="start-calendar" class="form-control bg-white text-center">
  </div>
  <div class="input-group col-sm-6 pl-sm-3 mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">終了</span>
    </div>
    <input type="text" id="end-calendar" class="form-control bg-white text-center">
  </div>
</div>

<div class="row">
  <div class="col-6 col-sm-3">
    <input type="button" value="過去１週間" id="a-week-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去２週間" id="two-weeks-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去１ヶ月" id="a-month-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去３ヶ月" id="three-months-button" class="btn btn-success btn-block mt-3">
  </div>
</div>

<%# グラフ描写エリア %>
<canvas id="chart-weight" class="mt-5"></canvas>

<br><%#
<input type="button" value="体重60kg以上" id="weigth-more-button" class="btn btn-success btn-block mt-3">
%>
<%
=begin
>%
<dl class="searchbox">
  <%= search_form_for(@q, url: graph_path) do |f| %>
  <div class="flex margin-top-10">
    <p><dt><%= f.label :weight, '体重' %></dt></p>
    <div class="input_space flex">
    <p><dd><%= f.search_field :weight_gteq %>  kg以上</dd></p>
    </div>
  </div>
    <%= f.submit "検索", class: 'search-btn' %>
  <% end %>
</dl>
<%
=end
%>

app/views/homes/top.html.erb
<body id="top">
  <div class="top-text">
    <p><h2>適切な体重管理で健康づくりをしましょう！</h2></p>
    <p>日々の体重のデータを可視化する事で生活習慣を見直すきっかけに！</p>
    <p>体重の記録が簡単に行えます。</p>
  </div>

  <br><br>
    <p><%= link_to 'ゲストログイン(閲覧用)', users_guest_sign_in_path, method: :post, class: 'btn btn-info btn-block btn-outline-light w-50' %></p>
    <br>
    <p><%= link_to 'ログイン', new_user_session_path, class: 'btn btn-secondary btn-block btn-outline-light w-50' %></p>
    <p><%= link_to '新規登録', new_user_registration_path, class: 'btn btn-dark btn-block btn-outline-light w-50' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>体重管理アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/header' %>
    </header>
      <!-- ログイン関連ページ以外にフラッシュ表示部分を追加 -->
      <% if controller_name = 'graphs' %>
        <%= render 'shared/flash_messages' %>
      <% end %>
        <div class="graph-container py-4 <%= devise_controller? ? 'mw-md' : 'mw-xl' %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <%= link_to "体重管理アプリ", graphs_path, class: 'navbar-brand' %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">

      <!-- ドロップダウン/右寄せ -->
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">設定
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'プロフィール', user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'アカウント編集', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to 'ログアウト', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table>
  <thead>
  <tr>
    <th scope="col">No.</th>
    <th scope="col">ユーザー名</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each.with_index(1) do |user, i| %>
    <tr>
      <th scope="row"><%= i %></th>
      <td><%= user.username %></td>
      <td>
        <%= link_to "編集", edit_user_path(user) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="center-block">
  <h1>プロフィール</h1><br>
    <p><img src=<%= @user.avatar.url%> class="profile_image"></p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col"><%= @user.username %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">年齢</th>
        <td><%= @user.age %> 歳</td>
      </tr>
      <tr>
        <th scope="row">性別</th>
        <td><%= @user.gender %></td>
      </tr>
      <tr>
        <th scope="row">身長</th>
        <td><%= @user.height %> cm</td>
      </tr>
      <tr>
        <th scope="row">現在体重</th>
        <td><%= @user.weight %> kg</td>
      </tr>
      <tr>
        <th scope="row">目標体重</th>
        <td><%= @user.target_weight %> kg</td>
      </tr>
      <tr>
        <th scope="row">目標体脂肪率</th>
        <td><%= @user.target_body %> %</td>
      </tr>
      <tr>
        <th scope="row">自己紹介</th>
        <% if @user.profile.nil? %>
          <td><%= @user.profile %></td>
        <% else %>
          <td><%= safe_join(@user.profile.split("\n"),tag(:br)) %></td>
        <% end %>
      </tr>
    </tbody>
  </table>



  <div class="form-group my-5">
    <p><%= link_to "トップページ", graphs_path, class: 'btn btn-dark w-50' %></p>
  </div>
</div>